# Generated by Django 5.2.1 on 2025-05-20 19:10

import api.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_topic_file_alter_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=api.models.topic_upload_to),
        ),
    ]
