# Generated by Django 5.2.1 on 2025-06-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_topic_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
